version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Jakarta"
    target-branch: "main"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Jakarta"
    target-branch: "main"
    open-pull-requests-limit: 5
